### ISSUE TITLE
Image spawning fteqwsv instance

### ISSUE THREAD

**Issue by fdittz** [FortressOne/map-repo#55]
As we launch the containers using docker-compose an fteqwsv instance is created by the map-repo container:
`2f998bdce97a43bbfbffffcf47d073f5ea785f9c7721a42c3db55650456ae5d6   fortressone/map-repo:latest        "/fortressonesv/fteqw-sv -ip localhost +set hostname FortressOne +exec fo_pubmode.cfg +map 2fort5r"	 7 seconds ago       Up 6 seconds        27500/tcp, 27500/udp   docker-server_map-repo_1                                   
`

**Comment by drzel** [comment]
should be fixed
